#!/bin/sh
#
# Start initialize
#

case "$1" in
  start)
    /bin/mcu_daemon & > /dev/null 2>&1
    echo -n "Starting initialize system: "
    fstmp=`cat /proc/mounts | grep "tmpfs" | grep "/media"`
    if [ $? != "0" ]; then
        mount -t tmpfs tmpfs /media -o size=512k
        mkdir -p /media/AFPSDcard
    fi
    echo 87 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio87/direction
    echo 1 > /sys/class/gpio/gpio87/value
    mount -t debugfs debugfs /sys/kernel/debug/
    echo 32786 > /proc/sys/fs/inotify/max_user_watches
    echo 67108864 > /proc/sys/net/core/rmem_max
    echo 67108864 > /proc/sys/net/core/wmem_max
    echo "4096 87380 67108864" > /proc/sys/net/ipv4/tcp_rmem
    echo "4096 65536 67108864" > /proc/sys/net/ipv4/tcp_wmem
    echo "2" > /proc/sys/net/ipv4/tcp_frto_response
    echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
    echo 30 > /proc/sys/net/ipv4/tcp_keepalive_intvl
    echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes
    echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
    echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
    echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save
    echo 1 > /proc/sys/vm/oom_kill_allocating_task
    echo 15360 > /proc/sys/vm/min_free_kbytes
    echo 200 > /proc/sys/vm/vfs_cache_pressure
    ln -sf /tmp /var/tmp
    echo "192.168.60.1" > /tmp/resolv.conf
    echo "OK"
	;;
  stop)
    echo -n "Stopping initialize system: "
    umount /sys/kernel/debug/
    echo "OK"
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
