#!/bin/sh
#
# Start netatalk
#

start() {
    echo "Starting Netatalk"
    mkdir -p /tmp/netatalk-db
    cp -Ra /usr/var/netatalk-org/* /usr/var/netatalk/
    start-stop-daemon -S -q -p /var/run/netatalk.pid --exec /usr/sbin/netatalk
}

stop(){
    echo "Stopping Netatalk"
    start-stop-daemon -K -q -p /var/run/netatalk.pid
    killall netatalk
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
#        start
        stop
	start
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

