#!/bin/sh
#
# Start initialize
#

case "$1" in
  start)
    
	;;
  stop)
  	killall rsync
   	sed -i 's/TransferStatus=.*/TransferStatus=completed/' /etc/nas/config/sdcard-transfer-status.conf
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
