WDPACKAGE_WEBUI_VERSION = 1.3.0-565
WDPACKAGE_WEBUI_RELEASE_DATE = 2014-09-18
WDPACKAGE_WEBUI_SOURCE = ui-$(WDPACKAGE_WEBUI_VERSION).deb

define WDPACKAGE_WEBUI_EXTRACT_CMDS
	dpkg-deb -R $(DL_DIR)/$(WDPACKAGE_WEBUI_SOURCE) $(TARGET_DIR)/
	rm -Rf $(TARGET_DIR)/DEBIAN
	sed -i 's/UI_.*/UI_'$(WDPACKAGE_WEBUI_VERSION):$(WDPACKAGE_WEBUI_RELEASE_DATE)'/' $(TARGET_DIR)/etc/version.packages
endef

define WDPACKAGE_RESTAPI_UNINSTALL_TARGET_CMDS
	rm -f $(TARGET_DIR)/var/local/bin
	rm -f $(TARGET_DIR)/var/local/sbin
endef

$(eval $(generic-package))
