#!/bin/sh
#
# Start the network....
#

case "$1" in
    start)
        echo "Starting network..."
        export $(cat /etc/config/wifi-config)    
        iw phy0 interface add wlan1 type managed 
        ifconfig $AP_IFACE $AP_IP netmask $AP_MASK up
        /sbin/ifup -a
        ;;
    stop)
        echo -n "Stopping network..."
        /sbin/ifdown -a
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
