#!/bin/bash
##################################################
### Author: Rance Lin                          ###
### Update: 2013-10-21                         ###
##################################################
: << !Command!
Restart all wifi service, include STA & AP mode.
Usage:
    - Edit "/etc/config/wifi-config" file.
    - Excute this shell script, "# wifi-restart".

Notice:
    - WPA3 is mean "WPA AUTO (1&2)".

ToDo:

!Command!



### Default Setting ###
DHCPD_CONF_PATH="/etc/dhcpd.conf"
HOSTAPD_CONF_PATH="/etc/hostapd/hostapd.conf"
WPA_SUPPLICANT_PATH="/etc/wpa_supplicant.conf"

HOSTPAD_SERVICE="/etc/init.d/S60hostapd"
DHCP_SERVICE="/etc/init.d/S80dhcp-server"
MULTI_ROLE_SERVICE="/etc/init.d/S90multi-role"



### Get Wifi Value ###
GET_WIFI_ENV_VALUE()
{
    export $(cat /etc/config/wifi-config)

    AP_SUBNET="${AP_IP%.*}.0"
    AP_DHCP_UPPER_BOUND="${AP_IP%.*}.100"
    AP_DHCP_LOWER_BOUND="${AP_IP%.*}.200"
}



### Change DHCP Config ###
CHANGE_DHCP_CONFIG()
{
    sed -i '111,$d' $DHCPD_CONF_PATH

    echo "option routers $AP_IP;"                                   >> $DHCPD_CONF_PATH
    echo "option domain-name-servers $AP_IP;"                       >> $DHCPD_CONF_PATH
    echo " "                                                        >> $DHCPD_CONF_PATH
    echo "subnet $AP_SUBNET netmask $AP_MASK {"                     >> $DHCPD_CONF_PATH
    echo "    pool {"                                               >> $DHCPD_CONF_PATH
    echo "        max-lease-time 600;"                              >> $DHCPD_CONF_PATH
    echo "        range $AP_DHCP_UPPER_BOUND $AP_DHCP_LOWER_BOUND;" >> $DHCPD_CONF_PATH
    echo "        option routers $AP_IP;"                           >> $DHCPD_CONF_PATH
    echo "        option domain-name-servers $AP_IP, $AP_DNS;"      >> $DHCPD_CONF_PATH
    echo "        allow unknown-clients;"                           >> $DHCPD_CONF_PATH
    echo "    }"                                                    >> $DHCPD_CONF_PATH
    echo "}"                                                        >> $DHCPD_CONF_PATH
}



### Change Hostapd Config ###
CHANGE_HOSTAPD_CONFIG()
{
    sed -i '1,1c \'interface=$AP_IFACE   $HOSTAPD_CONF_PATH
    sed -i '2,2c \'ssid=$AP_SSID_NAME    $HOSTAPD_CONF_PATH
    sed -i '4,4c \'channel=$AP_CHANNEL   $HOSTAPD_CONF_PATH

    case $AP_ENCRYPTION_TYPE in
        NONE )
            sed -i '74,$d' $HOSTAPD_CONF_PATH
            ;;
        WEP )
            sed -i '74,$d' $HOSTAPD_CONF_PATH

            echo "wep_default_key=0"                                >> $HOSTAPD_CONF_PATH
            echo "wep_key0=$AP_ENCRYPTION_KEY"                      >> $HOSTAPD_CONF_PATH
            ;;
        WPA1 )
            sed -i '74,$d' $HOSTAPD_CONF_PATH

            echo "wpa=1"                                            >> $HOSTAPD_CONF_PATH
            echo "wpa_passphrase=$AP_ENCRYPTION_KEY"                >> $HOSTAPD_CONF_PATH
            echo "wpa_key_mgmt=WPA-PSK"                             >> $HOSTAPD_CONF_PATH
            echo "wpa_pairwise=CCMP TKIP"                           >> $HOSTAPD_CONF_PATH
            echo "rsn_pairwise=CCMP"                                >> $HOSTAPD_CONF_PATH

            ;;
        WPA2 )
            sed -i '74,$d' $HOSTAPD_CONF_PATH

            echo "wpa=2"                                            >> $HOSTAPD_CONF_PATH
            echo "wpa_passphrase=$AP_ENCRYPTION_KEY"                >> $HOSTAPD_CONF_PATH
            echo "wpa_key_mgmt=WPA-PSK"                             >> $HOSTAPD_CONF_PATH
            echo "wpa_pairwise=CCMP TKIP"                           >> $HOSTAPD_CONF_PATH
            echo "rsn_pairwise=CCMP"                                >> $HOSTAPD_CONF_PATH
            ;;
        WPA3 )
            sed -i '74,$d' $HOSTAPD_CONF_PATH

            echo "wpa=3"                                            >> $HOSTAPD_CONF_PATH
            echo "wpa_passphrase=$AP_ENCRYPTION_KEY"                >> $HOSTAPD_CONF_PATH
            echo "wpa_key_mgmt=WPA-PSK"                             >> $HOSTAPD_CONF_PATH
            echo "wpa_pairwise=CCMP TKIP"                           >> $HOSTAPD_CONF_PATH
            echo "rsn_pairwise=CCMP"                                >> $HOSTAPD_CONF_PATH
            ;;
        *)
            ;;
    esac
}



### Change WPA Supplicant Config ###
CHANGE_WPA_SUPPLICANT_CONFIG()
{
    sed -i '5,$d' $WPA_SUPPLICANT_PATH

    case $STA_SECURITY_MODE in 
        "NONE" )
            echo "  ssid=\"$STA_SSID_NAME\""                        >> $WPA_SUPPLICANT_PATH
            echo "  key_mgmt=NONE"                                  >> $WPA_SUPPLICANT_PATH
            echo "}"                                                >> $WPA_SUPPLICANT_PATH
            ;;
        "WEP" )
            echo "  ssid=\"$STA_SSID_NAME\""                        >> $WPA_SUPPLICANT_PATH
            echo "  key_mgmt=NONE"                                  >> $WPA_SUPPLICANT_PATH
            echo "  wep_tx_keyidx=0"                                >> $WPA_SUPPLICANT_PATH
            echo "  wep_key0=$STA_WEP_KEY"                          >> $WPA_SUPPLICANT_PATH
            echo "}"                                                >> $WPA_SUPPLICANT_PATH
            ;;
        "WPA" | "WPA2" )
            echo "  ssid=\"$STA_SSID_NAME\""                        >> $WPA_SUPPLICANT_PATH
            echo "  psk=\"$STA_PSK_KEY\""                           >> $WPA_SUPPLICANT_PATH
            echo "}"                                                >> $WPA_SUPPLICANT_PATH
            ;;
        * )
            ;;
    esac
}



### Restart Wifi Service ###
RESTART_WIFI_SERVICE()
{
    $HOSTPAD_SERVICE restart
    $DHCP_SERVICE  restart
    $MULTI_ROLE_SERVICE restart
}



### Finished Message ###
FINISHED_MESSAGE()
{
    echo "==============================="
    echo "Restart Wifi Service Successed."
    echo "==============================="
}



##################################################
##################################################
##################################################
### Main Script ###
GET_WIFI_ENV_VALUE

CHANGE_DHCP_CONFIG

CHANGE_HOSTAPD_CONFIG

CHANGE_WPA_SUPPLICANT_CONFIG

RESTART_WIFI_SERVICE

FINISHED_MESSAGE
